### ISSUE TITLE
Error trying create new a Patient or Customer

### ISSUE THREAD

**Issue by system19** [ESS-LLP/erpnext#14]
Trying to create a new Customer I get the error:
Something went wrong
Server Error: Please check your server logs or contact tech support.

Trying to create a new Patient I get the error:
DocType Patient Admission not found
The resource you are looking for is not available

Trying to create a new Physician I get the error:
Something went wrong
Server Error: Please check your server logs or contact tech support.

Am running ERPNext 8.0.27 and Frappe 8.0.69

Anyone else having the same issue?

**Comment by rkurungadam** [comment]
Fixed this, have rebased with frappe/erpnext.
