### ISSUE TITLE
Canceling consultation and lab test records in Healthcare

### ISSUE THREAD

**Issue by mafrica** [ESS-LLP/erpnext#18]
Despite having all the necessary permissions I am unable to cancel (then delete) consultation and lab test  records ie the pull down menu does not show the cancel option.
![capture1](https://user-images.githubusercontent.com/23632469/37087424-43fa47fe-220b-11e8-8b8a-1efe6cea9030.PNG)
![capture2](https://user-images.githubusercontent.com/23632469/37087427-47853168-220b-11e8-8c11-4c053ff7a623.PNG)
![capture3](https://user-images.githubusercontent.com/23632469/37087428-48ef1140-220b-11e8-9142-236f40cd2a0e.PNG)
![capture4](https://user-images.githubusercontent.com/23632469/37087433-4a849b06-220b-11e8-94f7-7c4396a5c083.PNG)

**Comment by rkurungadam** [comment]
Hi, Have fixed consultation, you should be able to see cancel once the above PR is merged. Not sure what is wong with Lab Test, they can be cancelled. Also please raise issues at github.com/frappe/erpnext/issues  hereafter.
Thanks
