### ISSUE TITLE
After creating the invoice for drug, the checkbox doesn't disappear, allowing creation of multiple invoices

### ISSUE THREAD

**Issue by sathishpy** [ESS-LLP/erpnext#3]
Once a lab test is created from the service desk and invoiced, the check box disappears. However it doesn't happen for drug prescription, allowing creation of multiple invoices for the same prescription.

**Comment by akurungadam** [comment]
Prescribed medicines could be invoiced more than once / in part.. and there could be many such validations to handle test cases which are not dealt with.

**Comment by sathishpy** [comment]
This is the flow I am imagining:
1. The doctor prescribes the drugs. Perhaps he gets to know the stock during prescription itself, so could chose to change the medicine in case of stock issues.
2. The patient goes to pharmacy, to collect the medicine. Now there could be couple of scenarios:
a. Patient decides to omit some drugs because he already have
b. Patient decides to reduce the count because of monitory issues
c. The stock isn't available
All these might need to handle part of the invoice. However the best approach to handle such scenarios would be to print the doctor prescribed medication and then submit the updated sales invoice as per what customer is going to receive. The part invoice isn't of much use as the patient's consultation is over. The doctor has the record of what is issued and perhaps can also access what is delivered to patient.

**Comment by akurungadam** [comment]
1 - Ideally, the doctor prescribes generic drugs and the pharmacy disperses according to availability / patient preference. (Right now the prescription form allows to select Items - we can change this to Item templates / product variants and dosage strength selections and then Invoicing variants, brand etc.)
2 - I'm not sure i quite understand this - but the physician do not currently have a way to see what the patient is invoiced - other than through the standard ERPNext Stock / Sales reports.

**Comment by sathishpy** [comment]
Thanks.
1. That looks fine. I suppose it doesn't change the approach I suggested earlier. ie 
a. create the invoice once(from service desk or automatically).
b. Allow pharmacist to update the invoice before submitting
c. Dispense the items based on the submitted invoice
This resolves the recurring invoice creation issue I mentioned
2. Right. I don't think it is really required, but if needed Physician could be allowed access to patients standard sales invoice

**Comment by akurungadam** [comment]
if at all you think you need the stock balance to be displayed in the drug prescriptions, you can use stock.utils.get_stock_balance to fetch the current stock
