### ISSUE TITLE
sample collection isn't working even though 'Manage sample collection' is set

### ISSUE THREAD

**Issue by sathishpy** [ESS-LLP/erpnext#4]
I have set the 'Manage sample collection' checkbox in 'Laboratory settings', expecting that will create a 'sample collection' task. However after Lab Test is created from service desk, I don't see any 'Sample collection' tasks. So not really sure how this is supposed to work.

**Comment by akurungadam** [comment]
you'll have etc configure the sample in the Lab Test template. Else, the sample collection document won't be created.

**Comment by sathishpy** [comment]
BTW issue #4From:earthians Software Services LLP
can you check if the sample is selected in LabTest Template

It was't set. So I will add that and check again....

**Comment by sathishpy** [comment]
I have tested this after configuring the sample and it is working. Thanks.
