### ISSUE TITLE
setup wizard fails for healthcare domain installation 

### ISSUE THREAD

**Issue by Salmon-Bard** [ESS-LLP/erpnext#6]
When selection "healthcare" domain during installation of erpnext the final processing fails after gonging through all steps and pages. 

Doing so inspection in browser it seems that jquery can not access a url.
Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)

Server log shows that sockt.io can not access client resource.

2017/05/15 14:18:59 [error] 4825#4825: *52 connect() failed (111: Connection refused) while connecting to upstream, client: 86.108.20.246, server: site1.local, request$

I have tested other domain installations and they all complete without issues.

Any help is appreciated .

**Comment by akurungadam** [comment]
rebased to latest ERPNext develop. Anyways, we are in the process of the merge to core - many of the documents are being redesigned. And some of the features, especially inpatient related stuff, aren't going to be merged. The current timeline for completion is end of May. 

Will update here when we are close.. I would suggest you to hold you tests for the time being or use the demo instance.

**Comment by Salmon-Bard** [comment]
Thanks for the update and wish you success on this great project.
