### ISSUE TITLE
docker deploy?

### ISSUE THREAD

**Issue by jujes** [ESS-LLP/erpnext#7]
Hi, some one know how deploy it using docker??

I try with https://github.com/Ridhosribumi/docker-erpnext scripts
adding this forked version of erpnext but don't successes...

here the ERPNEXT_APPS_JSON= pointing to this repo

`https://gist.githubusercontent.com/jujes/e99a01b0eb47d082b152346bc43cd7d8/raw/4d9772c0f65f062325272d4f7f5d22dec8c097cf/erpnext-healthcare-master.json`

Thanks in advance,

**Comment by akurungadam** [comment]
healthcare is on develop branch

**Comment by jujes** [comment]
@akurungadam what that mean?

> healthcare is on develop branch

As I mentioned, I need a way to deploy erpnext using your forked repo (develop branch if you want) whit docker. I found the Ridhosribumi/docker-erpnext scripts to help me but need someone who tell me how do it... instead use erpnext repo, use erpnext-healthcare...

thanks in advance,

**Comment by akurungadam** [comment]
try updating your ERPNEXT_APPS_JSON to

{
	"url":"https://github.com/ESS-LLP/erpnext-healthcare",
	"name":"erpnext-healthcare",
	"branch": "develop"
}

**Comment by jujes** [comment]
@akurungadam I tried it...
https://gist.githubusercontent.com/jujes/e99a01b0eb47d082b152346bc43cd7d8/raw/df2eddd924156963e31612a54b31664632b39ac2/erpnext-healthcare-master.json

Actually I create my own docker container using your advice and get the normal erpnext running...

**docker pull jujes/healthcare:dev**

**docker run -d --name healthcare  -p 80:80 jujes/healthcare:dev**

**auth:
user: administrator
pass: 12345678**

![healthcare 00](https://cloud.githubusercontent.com/assets/2881017/26161238/a742a72c-3b23-11e7-8b07-7ceaf1e6534f.png)

![healthcare 01](https://cloud.githubusercontent.com/assets/2881017/26161248/ad6706e8-3b23-11e7-85ab-75ea37e7a142.png)

can you tell me how make this image using your develop branch?

thanks in advance,

**Comment by akurungadam** [comment]
Did you point the ERPNEXT_APPS_JSON in the docker file to yours?
https://gist.githubusercontent.com/jujes/e99a01b0eb47d082b152346bc43cd7d8/raw/df2eddd924156963e31612a54b31664632b39ac2/erpnext-healthcare-master.json

**Comment by jujes** [comment]
yes, I pointed to my [erpnext-healthcare-master.json](https://gist.githubusercontent.com/jujes/e99a01b0eb47d082b152346bc43cd7d8/raw/df2eddd924156963e31612a54b31664632b39ac2/erpnext-healthcare-master.json) in the docker [ERPNEXT_APPS_JSON](https://github.com/Ridhosribumi/docker-erpnext/blob/master/Dockerfile#L7)

please check it with my Dockerfile

```
MAINTAINER lukptr <lukptr@ridhosribumi.com>
ENV FRAPPE_USER=frappe \
    MYSQL_PASSWORD=12345678 \
    ADMIN_PASSWORD=12345678 \
    ERPNEXT_APPS_JSON=https://gist.githubusercontent.com/jujes/e99a01b0eb47d082b152346bc43cd7d8/raw/df2eddd924156963e31612a54b31664632b39ac2/erpnext-healthcare-master.json \
    DEBIAN_FRONTEND=noninteractive
RUN useradd $FRAPPE_USER && mkdir /home/$FRAPPE_USER && chown -R $FRAPPE_USER.$FRAPPE_USER /home/$FRAPPE_USER
WORKDIR /home/$FRAPPE_USER
RUN wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py && sed -i "s/'', ''/'$MYSQL_PASSWORD', '$ADMIN_PASSWORD'/g" install.py
COPY setup.sh /
RUN bash /setup.sh
COPY all.conf /etc/supervisor/conf.d/
EXPOSE 80
CMD ["/usr/bin/supervisord","-n"]%
```

**Comment by jujes** [comment]
Hi @akurungadam 
nothing yet?
:)

**Comment by rkurungadam** [comment]
Hi @jujes 
edit: 'python install.py --production' guess you have this line in setup.sh. If so remove parameter --production and try again.
Can you please check in the container what upstream of you erpnext is pointing to. If it is this repo and the branch is develop, you should have medical in domain selection.
