### ISSUE TITLE
Lab test template and item link failure

### ISSUE THREAD

**Issue by mudux** [ESS-LLP/erpnext#8]
I am having problem with the current version to invoice a new lab test .

When I try to create an invoice after creating a lab test it throws an error that the item doesnt exist when it actually does and appears in the item master.

please direct..

**Comment by akurungadam** [comment]
Could you please check if the item is disabled? If the "Is Billable" is unchecked in the Lab Test Template, the item is created but disabled.

**Comment by mudux** [comment]
I checked but all seems fine...

I imported Items list and similarly lab test templates from worked example...and also generated another test through the 'new lab test template' but both had the same outcome.

I have attached here some screenshots for your information..

![item](https://cloud.githubusercontent.com/assets/28738740/26153193/ff128262-3b12-11e7-97de-18d5247fa420.jpg)

![lab test template](https://cloud.githubusercontent.com/assets/28738740/26153227/1ec0f1d4-3b13-11e7-83ae-d8dc34ec96bc.jpg)

![new lab test](https://cloud.githubusercontent.com/assets/28738740/26153233/280a3f48-3b13-11e7-911d-7f756f085fbe.jpg)

![item not found](https://cloud.githubusercontent.com/assets/28738740/26153241/2f86d04c-3b13-11e7-88e3-c1608edcad46.jpg)

**Comment by pjamsheer** [comment]
Bug fixed. 
Please update  and Confirm.
Thank you.

**Comment by mudux** [comment]
solved..thnx
