### ISSUE TITLE
drugs prescribed dont automatically add to an invoice

### ISSUE THREAD

**Issue by mudux** [ESS-LLP/erpnext#9]
drugs prescribed dont automatically add to an invoice,...is this intentional due to development progress?

**Comment by akurungadam** [comment]
yes, this is by design. All invoicing is manual.

**Comment by mudux** [comment]
I would assume for the sake of ease of work, the prescribed drugs can be pulled into an invoice or a sales order similar to ' lab tests-> create invoice ' option.

Is there a different way to do this instead of inserting every drug prescribed into the system again for invoicing purposes?

**Comment by akurungadam** [comment]
yes, there should be.. it's missing at present, we'll add this to the list we are working on.

**Comment by mudux** [comment]
great.
